version: "3.7"
services:
  php-apache:
    build: './docker/services/php-apache'
    depends_on:
      - mysql
    networks:
      - demo-crud-php
    ports: 
      - "80:80"
    volumes:
      - ./src/:/var/www/html/
  mysql:
    image: mysql:5.7
    networks:
      - demo-crud-php
    environment:
      MYSQL_DATABASE: demo-crud-php
      MYSQL_PASSWORD: 123mudar
      MYSQL_ROOT_PASSWORD: 123mudar 
      MYSQL_USER: demo-crud-php
    ports: 
      - "3306:3306"
networks:
  demo-crud-php:
